
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class FrmChuyenKhoan extends javax.swing.JFrame {

    FrmGiaoDich frmGD;  // Add this field

    public FrmChuyenKhoan(FrmGiaoDich frmGiaoDich) {
        this.frmGD = frmGiaoDich;
        initComponents();
    }

    khachhangBean khb = FrmDangNhap.khb;
    ITinhToan se = FrmDangNhap.server;

    static String sOdU;

    /**
     * Creates new form FrmChuyenKhoan
     */
    public FrmChuyenKhoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSoTKNhan = new javax.swing.JTextField();
        txtSoTienChuyen = new javax.swing.JTextField();
        btnChuyenTien = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSoDuTK = new javax.swing.JTextField();
        btn200 = new javax.swing.JButton();
        btn500 = new javax.swing.JButton();
        btn1tr = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        btn100 = new javax.swing.JButton();
        btn2tr = new javax.swing.JButton();
        btn3tr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTenTKNhan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CHUYEN KHOAN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("So Tai Khoan Nhan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("So Tien Chuyen");

        txtSoTKNhan.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtSoTKNhan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoTKNhanFocusLost(evt);
            }
        });

        txtSoTienChuyen.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtSoTienChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoTienChuyenActionPerformed(evt);
            }
        });

        btnChuyenTien.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnChuyenTien.setText("Chuyen Tien");
        btnChuyenTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenTienActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("So Du TK");

        txtSoDuTK.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtSoDuTK.setEnabled(false);

        btn200.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn200.setText("200.000");
        btn200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200ActionPerformed(evt);
            }
        });

        btn500.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn500.setText("500.000");
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });

        btn1tr.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn1tr.setText("1.000.000");
        btn1tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1trActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Quay Lai");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btn100.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn100.setText("100.000");
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });

        btn2tr.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn2tr.setText("2.000.000");
        btn2tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2trActionPerformed(evt);
            }
        });

        btn3tr.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn3tr.setText("3.000.000");
        btn3tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3trActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ten Tai Khoan Nhan");

        txtTenTKNhan.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtTenTKNhan.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnQuayLai)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnChuyenTien)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSoTKNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btn100)
                                        .addComponent(jLabel4)
                                        .addComponent(btn200)
                                        .addComponent(btn500))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoTienChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(txtTenTKNhan)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSoDuTK, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn2tr, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn1tr, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn3tr, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuayLai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoDuTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoTKNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenTKNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoTienChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn100)
                    .addComponent(btn1tr))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2tr)
                    .addComponent(btn200))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn500)
                    .addComponent(btn3tr))
                .addGap(33, 33, 33)
                .addComponent(btnChuyenTien)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setSoDu(String sodu) {
        txtSoDuTK.setText(sodu);
    }


    private void btn200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200ActionPerformed
        txtSoTienChuyen.setText("200000");
    }//GEN-LAST:event_btn200ActionPerformed

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        txtSoTienChuyen.setText("500000");
    }//GEN-LAST:event_btn500ActionPerformed

    private void btn1trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1trActionPerformed
        txtSoTienChuyen.setText("1000000");
    }//GEN-LAST:event_btn1trActionPerformed

    private void btnChuyenTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenTienActionPerformed
        try {
            String tkn = txtSoTKNhan.getText();
            String tien = txtSoTienChuyen.getText();
            String ttkn = txtTenTKNhan.getText();

            if (tkn.equals("") && tien.equals("") && ttkn.equals("")) {
                JOptionPane.showMessageDialog(this, "Cac truong nay la bat buoc");
            } else {

                if (tien.equals("") && !tkn.equals("") && !ttkn.equals("")) {
                    JOptionPane.showMessageDialog(this, "Vui long nhap so tien");
                } 
//                else if(!tien.equals("") && !tkn.equals("") && !ttkn.equals("")){
//                    JOptionPane.showMessageDialog(this, "Vui long nhap stk nguoi nhan");
//                }
                else {
                    int stc = Integer.valueOf(txtSoTienChuyen.getText());
                    if (stc >= 20000000) {
                        JOptionPane.showMessageDialog(this, "So tien chuyen vuot qua cho phep");
                    } else if (stc <= 0) {
                        JOptionPane.showMessageDialog(this, "Khong the chuyen khoan so tien am");
                    } else if (tkn.equals(khb.SoTaiKhoan.trim())) {
                        JOptionPane.showMessageDialog(this, "Khong the chuyen khoan cho chinh chu");
                    } else {
                        if (se.KTSoDu(khb.SoTaiKhoan, stc)) {
                            if (se.ChuyenKhoan(khb.SoTaiKhoan, tkn, stc)) {
                                se.TruTien(khb.SoTaiKhoan, stc);
                                se.CongTien(tkn, stc);
                                int SoDu = Integer.valueOf(txtSoDuTK.getText());
                                int con = SoDu - stc;
                                txtSoDuTK.setText(String.valueOf(con));
                                JOptionPane.showMessageDialog(this, "Chuyen khoan thanh cong");
                            } else {
                                JOptionPane.showMessageDialog(this, "Loi chuyen khoan");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "So du khong du de chuyen");
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnChuyenTienActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (khb != null) {
            setSoDu(FrmGiaoDich.sodu);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        sOdU = txtSoDuTK.getText();
        frmGD.updateSoDu(sOdU);
        frmGD.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        txtSoTienChuyen.setText("100000");
    }//GEN-LAST:event_btn100ActionPerformed

    private void btn2trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2trActionPerformed
        txtSoTienChuyen.setText("2000000");
    }//GEN-LAST:event_btn2trActionPerformed

    private void btn3trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3trActionPerformed
        txtSoTienChuyen.setText("3000000");
    }//GEN-LAST:event_btn3trActionPerformed

    private void txtSoTKNhanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoTKNhanFocusLost
        String tkn = txtSoTKNhan.getText();
        try {
            khachhangBean khk = new khachhangBean();
            khk = se.Kttk(tkn);
            if (txtSoTKNhan.equals("")) {
                JOptionPane.showMessageDialog(this, "Nhap so tai khoan nguoi nhan");
            } else if (khk.SoTaiKhoan == null) {
                JOptionPane.showMessageDialog(this, "Ten tai khoan nhan khong ton tai");
            } else {
                txtTenTKNhan.setText(khk.HoTen);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(FrmChuyenKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSoTKNhanFocusLost

    private void txtSoTienChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoTienChuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoTienChuyenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChuyenKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn1tr;
    private javax.swing.JButton btn200;
    private javax.swing.JButton btn2tr;
    private javax.swing.JButton btn3tr;
    private javax.swing.JButton btn500;
    private javax.swing.JButton btnChuyenTien;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtSoDuTK;
    private javax.swing.JTextField txtSoTKNhan;
    private javax.swing.JTextField txtSoTienChuyen;
    private javax.swing.JTextField txtTenTKNhan;
    // End of variables declaration//GEN-END:variables
}
