
import java.io.Console;
import java.rmi.Naming;
import java.sql.Connection;
import javax.print.attribute.standard.Severity;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class FrmDangNhap extends javax.swing.JFrame {
//    public String[] ip = {"192.168.1.10"};

    public String ip = "192.168.100.36";
    static khachhangBean khb;
    static ITinhToan server;
    int dem = 0, dem1 = 0;

    /**
     * Creates new form FrmDangNhap
     */
    public FrmDangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSoTK = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMaPin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("So Tai Khoan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Ma pin");

        txtSoTK.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N

        btnDangNhap.setText("Dang nhap");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("DANG NHAP");

        txtMaPin.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtMaPin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDangNhap)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaPin)
                                    .addComponent(txtSoTK, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSoTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnDangNhap)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed

        try {
            server = (ITinhToan) Naming.lookup("rmi://" + ip + "/TinhToan");
            String stk = txtSoTK.getText();
            String mp = txtMaPin.getText();

            khb = server.Ktdn(stk, mp);
            System.out.println(server.Kttk(stk));
            if (stk.equals("") && mp.equals("")) {
                dem1++;
                JOptionPane.showMessageDialog(this, "Cac truong nay la bat buoc");
                if (dem1 >= 3) {
                    JOptionPane.showMessageDialog(this, "Khoa giao dich vi ban xung dang");
                    txtMaPin.setEnabled(false);
                    txtSoTK.setEnabled(false);
                }
            } else if (server.Kttk(stk) == null){
                JOptionPane.showMessageDialog(this, "So tai khoan khong ton tai");
            } else if (mp.length() != 6) {
                JOptionPane.showMessageDialog(this, "Ma pin phai dung 6 ki tu");
            } else if (khb.SoTaiKhoan == null && server.Kttk(stk) != null) {
                dem++;
                JOptionPane.showMessageDialog(this, "Mat khau tai khoan sai");
                if (dem == 3) {
                    txtMaPin.setEnabled(false);
                    txtSoTK.setEnabled(false);
                    server.KhoaTK(false, stk);
                    JOptionPane.showMessageDialog(this, "Nhap mat khau sai qua 3 lan tai khoan bi khoa");   
                }

            } else if (khb.Khoa == false){
                JOptionPane.showMessageDialog(this, "Tai khoan da bi khoa khong the dang nhap");
            } else {
                if(!server.Kttt(stk))
                {
                    FrmDoiMaPin frmpin = new FrmDoiMaPin();
                    frmpin.setServer(server);

                    FrmGiaoDich frm = new FrmGiaoDich();
                    frm.setKhachhangBean(khb);
                    JOptionPane.showMessageDialog(this, "Dang nhap thanh cong");
                    server.CapNhatTT(khb.SoTaiKhoan);
                    frm.setVisible(true);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Tai khoan da dc dang nhap");
                }
            }

        } catch (Exception tt) {
            System.out.println(tt.getMessage());
            tt.printStackTrace();
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtMaPin;
    private javax.swing.JTextField txtSoTK;
    // End of variables declaration//GEN-END:variables
}
