
import java.rmi.RemoteException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class FrmLichSuGD extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    ITinhToan se = FrmDangNhap.server;
    khachhangBean khb = FrmDangNhap.khb;
    int SoCot = 4;

    /**
     * Creates new form FrmLichSuGD
     */
    public FrmLichSuGD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableLS = new javax.swing.JTable();
        choice1 = new java.awt.Choice();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TableLS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableLS);

        jTabbedPane1.addTab("Lich su giao dich", jScrollPane1);

        choice1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        choice1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choice1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void NapNgayChoice() {
        try {
            choice1.removeAll();
            List<String> ngay = se.LayNgay(khb.SoTaiKhoan);
            for (String n: ngay){
                choice1.add(n);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "loi ha");
        }
    }

    public void HienThiLsNgay(String Ngay) {
        try {
            model.setRowCount(0);
            ArrayList<ChiTietGiaoDichBean> ds = new ArrayList<>();
            ds = se.getlstn(khb.SoTaiKhoan, Ngay);
            Object[] t = new Object[SoCot];
            for (int i = 0; i < ds.size(); i++) {
                ChiTietGiaoDichBean ls = (ChiTietGiaoDichBean) ds.get(i);
                t[0] = ls.NgayGiaoDich;
                t[1] = String.valueOf(ls.SoTienGiaoDich);
                t[2] = ls.SoTaiKhoan;
                t[3] = ls.GhiChu;
                model.addRow(t);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "loi");
        }

    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            NapNgayChoice();
            model.addColumn("Ngay giao dich");
            model.addColumn("So tien giao dich");
            model.addColumn("So tai khoan");
            model.addColumn("Ghi chu");

            TableLS.setModel(model);
            //masv, hoten va Dtb;
            Object[] t = new Object[SoCot];
            ArrayList<ChiTietGiaoDichBean> ds = new ArrayList<>();
            ds = se.getls(khb.SoTaiKhoan);
            for (int i = 0; i < ds.size(); i++) {
                ChiTietGiaoDichBean ls = (ChiTietGiaoDichBean) ds.get(i);
                t[0] = ls.NgayGiaoDich;
                t[1] = String.valueOf(ls.SoTienGiaoDich);
                t[2] = ls.SoTaiKhoan;
                t[3] = ls.GhiChu;
                model.addRow(t);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

   
    private void choice1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choice1ItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            if (choice1.getItemCount() > 0) {
                String Ngay = choice1.getSelectedItem();
                HienThiLsNgay(Ngay);
            }
        }
    }//GEN-LAST:event_choice1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLichSuGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLichSuGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLichSuGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLichSuGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLichSuGD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableLS;
    private java.awt.Choice choice1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
