
import java.rmi.Naming;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class FrmHienThi extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel model2 = new DefaultTableModel();
    DefaultListModel<String> listMaLoai = new DefaultListModel<>();
    ArrayList<LopBean> dsl;
    //public String ip = "192.168.1.10";
    public String ip = "0.0.0.0";
    static SinhVienBean svb;
    static ITinhToan server;
    int socot = 5;
    int socot2 = 4;
    private ITinhToan selectse;
    /**
     * Creates new form FrmHienThi
     */
    public FrmHienThi() {
        initComponents();
    }

    void LoadSinhVien(ArrayList<SinhVienBean> ds) {
        model.setRowCount(0);
        for (SinhVienBean sv : ds) {
            Object[] t = new Object[socot];
            t[0] = sv.getMaSinhVien();
            t[1] = sv.getHoTen();
            t[2] =  String.valueOf(sv.getDiemLT());
            t[3] = String.valueOf(sv.getDiemTH());
            t[4] = sv.getMaLop();
            model.addRow(t);
        }
        TbSinhVien.setModel(model);
    }
    
    void LoadDonVi(ArrayList<LopBean> ds) {
        model2.setRowCount(0);
        for (LopBean dv : ds) {
            Object[] t = new Object[socot2];
            t[0] = dv.getMaLop();
            t[1] = dv.getTenLop();
            t[2] = String.valueOf(dv.getDem());
            t[3] = String.valueOf(dv.getTbc());
            //t[2] = dv.getTbc();
            model2.addRow(t);
        }
        TbLop.setModel(model2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTim = new javax.swing.JTextField();
        BtTimKiem = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbLop = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbSinhVien = new javax.swing.JTable();
        BtSXTang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BtTimKiem.setText("Tim Kiem");
        BtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTimKiemActionPerformed(evt);
            }
        });

        TbLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TbLop);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        TbSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TbSinhVien);

        jTabbedPane2.addTab("tab1", jScrollPane2);

        BtSXTang.setText("SX Tang Dan");
        BtSXTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSXTangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtSXTang)
                                .addGap(67, 67, 67)
                                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addComponent(BtTimKiem)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtTimKiem)
                    .addComponent(BtSXTang))
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            server = (ITinhToan) Naming.lookup("rmi://" + ip + "/TinhToan");
            //NapNgayChoice();
            model.addColumn("Ma Sinh Vien");
            model.addColumn("Ho Ten");
            model.addColumn("Diem LT");
            model.addColumn("Diem TH");
            model.addColumn("Ma Lop");

            TbSinhVien.setModel(model);

            ArrayList<SinhVienBean> ds = new ArrayList<>();
            ds = server.getSV();
            LoadSinhVien(ds);


            model2.addColumn("Ma Lop");
            model2.addColumn("Ten Lop");
            model2.addColumn("Tong sv");
            model2.addColumn("tbc");
            //model2.addColumn("Trung binh HSL");

            TbLop.setModel(model2);

            ArrayList<LopBean> ds1 = new ArrayList<>();
            ds1 = server.getL();
            LoadDonVi(ds1);

            selectse = (ITinhToan) Naming.lookup("rmi://" + ip + "/TinhToan");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void BtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTimKiemActionPerformed
        try {
            model.setRowCount(0);
            String Tim = txtTim.getText().trim();
            System.out.println(Tim);
            ArrayList<SinhVienBean> ds = new ArrayList<>();
            ds = selectse.HtTimKiem(Tim);
            LoadSinhVien(ds);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtTimKiemActionPerformed

    private void BtSXTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSXTangActionPerformed
        try {
            model.setRowCount(0);
            ArrayList<SinhVienBean> ds = new ArrayList<>();
            ds = selectse.SapXepDiemLTTang();
            LoadSinhVien(ds);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BtSXTangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHienThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHienThi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtSXTang;
    private javax.swing.JButton BtTimKiem;
    private javax.swing.JTable TbLop;
    private javax.swing.JTable TbSinhVien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
